### PR TITLE
Fix water vapor (Q) register incompatibility with initialize_constituents scheme

### PR DESCRIPTION
**Pull request by jimmielin**
Tag name (required for release branches):
Originator(s): @jimmielin

Description (include the issue title, and the keyword ['closes', 'fixes', 'resolves'] followed by the issue number):

Add `water_species` and `mixing_ratio_type = 'wet'` property for when `cam_register_constituents` registers water vapor when no other scheme explicitly uses water vapor (but might use all CCPP constituents as a whole)

Describe any changes made to build system: N/A

Describe any changes made to the namelist: N/A

List any changes to the defaults for the input datasets (e.g. boundary datasets): N/A

List all files eliminated and why: N/A

List all files added and what they do: N/A

List all existing files that have been modified, and describe the changes: 
(Helpful git command: `git diff --name-status development...<your_branch_name>`)

```
Add water_species = .true. and mixing_ratio_type = 'wet' to wv_stdname
M       src/control/cam_comp.F90
```

If there are new failures (compared to the `test/existing-test-failures.txt` file),
have them OK'd by the gatekeeper, note them here, and add them to the file.
If there are baseline differences, include the test and the reason for the
diff. What is the nature of the change? Roundoff?

derecho/intel/aux_sima:

derecho/gnu/aux_sima:

If this changes climate describe any run(s) done to evaluate the new
climate in enough detail that it(they) could be reproduced:

CAM-SIMA date used for the baseline comparison tests if different than latest:

### CODE REVIEW

**Comment by jimmielin** [comment]
When testing shallow convection with the `initialize_constituents` scheme to use all constituent data, I have found that the model fails to initialize with the error
```
 ERROR:
 cam_register_constituents: ccp_model_const_add_metadata ERROR: Trying to add co
 nstituent water_vapor_mixing_ratio_wrt_moist_air_and_condensed_water but an inc
 ompatible constituent with this name already exists at cam_comp.F90:638
```

Debugging in the CCPP constituents property module shows that the following logic in `cam_register_constituents`:
```fortran
      ! Check if water vapor is already marked as a constituent by the
      ! physics:
      call cam_ccpp_is_scheme_constituent(wv_stdname, is_constituent, errflg, errmsg)
...

      !If not requested by the physics, then add water vapor to the
      !constituents object:
      !-------------------------------------------
      if (.not. is_constituent) then
...

         ! Register the constituents so they can be advected:
         call host_constituents(1)%instantiate( &
              std_name=wv_stdname,              &
              long_name="water vapor mixing ratio w.r.t moist air and condensed_water", &
...
```

Does not add the `water_species` property whereas `initialize_constituents` does for `Q`, leading to the runtime crash. As water vapor is a water species, these properties are now added which allows the model to proceed.

**Review by peverwhee — APPROVED** [review]
yes - good call @jimmielin !

**Review by nusbaume — APPROVED** [review]
Thanks for fixing this @jimmielin!

**Comment by jimmielin** [comment]
Superseded by https://github.com/ESCOMP/atmospheric_physics/pull/185

**Pull request closed without merging**
